{% set name = "symfit" %}
{% set version = "0.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02381f00f2f183ade2d7b665e120ace7aab84c4e6b3b25615134e4235fa303d6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  
requirements:
  host:
    - pip
    - python
    - pbr >=1.9
  run:
    - python
    - numpy >=1.12
    - scipy >=1.0
    - sympy >=1.2
    - six
    - funcsigs  # [py2k]
    - functools32  # [py2k]

test:
  imports:
    - symfit

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symbolic Fitting; fitting as it should be.
  doc_url: http://symfit.readthedocs.org
  dev_url: https://github.com/tBuLi/symfit

extra:
  recipe-maintainers:
    - tbuli
