{% set version = "0.5.6" %}

package:
  name: symfit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/symfit/symfit-{{ version }}.tar.gz
  sha256: b8c97aa96f7e4a385adf8e22d532712e12be4ef845ec18b817e45efdc69eadf4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - python >=3.7
    - pip
    - pbr >=1.9
  run:
    - python >=3.7
    - numpy >=1.12
    - scipy >=1.0
    - sympy >=1.2
    - toposort
    - setuptools

test:
  imports:
    - symfit

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symbolic Fitting; fitting as it should be.
  doc_url: http://symfit.readthedocs.org
  dev_url: https://github.com/tBuLi/symfit

extra:
  recipe-maintainers:
    - tbuli
    - jhsmit
