appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: adqZWEE9Q6ia3N7ZgD1qLefR8uEgSU7cxjCF2qP0txacCA7hQpwBEwxkIX+DFi4exL24KX6MQG6R4C+TJaap4WQKf/EJ6C9ggDwdTdt+Y/CycxN5eauTJUSBEj7cUjvrfMBpVvCWhlRcD8jEml3OrMEB3k5Pla4BcftvEYvnI/98+VNMoP8VEoHPSySCFVfkS6GQRhIhfp9waYy4vr/E0ZrtSNjrbYLvDTLQjZPZ/3BEEc0vVKgzbEH0sTChDyPkRQHtAOrBbajZHcrxalK1BRfrn8ZC/6IKwyYGhPa2S94VyJA5rilAsXa7UrDAqZa6v5cu1Kg7RatqFeV6fN+tDaQg9ChDVSNLl5TXM+hummvA4gmCAvYfMYr9ZUErhmJlScg4r3tfkJyp4yHC7+jz1H+oiSNwdfAcuNndP7+TSVXBrRhgp1wZ6W/VckJwVRZ6pKnqdQyVn2AYbwndi8ScGdroPuFL3cIbSSoBibMBxB8y+dz3g0BYBAay/2lyLO4cocSNw5gNQN1iXaCxfZ354SlqLn0DWkH83NnCOVTkWxFYstJrgcykcoegpMQh383VexGXRpCojASsLJ4d2VcUzjU2niFjSEvMVEYu1j3XcH1E+Fc+ZDPW3YpFBer93BGCCqvIJzYQyttrZXCL7OhYgGtI2LpSBdS/CaNCvDQ5vPg=}
